# Generated by Django 2.2 on 2020-05-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0005_auto_20200523_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
