# Generated by Django 2.2 on 2020-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0008_auto_20200523_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='new.jpg', upload_to='product_img'),
        ),
    ]
